<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtA7Pkg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtA7Pkg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVtA7Pkg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVtA7Pkg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVtA7Pkg\App_KernelDevDebugContainer([
    'container.build_hash' => 'VtA7Pkg',
    'container.build_id' => 'a02da012',
    'container.build_time' => 1638176933,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtA7Pkg');
